export const insightCategories = [
  "Web Design",
  "Web Development",
  "WordPress",
  "Product Design",
  "UX/UI",
  "Technology",
  "Business",
  "Studio",
] as const;

export type InsightCategory = (typeof insightCategories)[number];
export type InsightStatus = "published" | "draft";
export type InsightCtaVariant = "website-review" | "project" | "product-support" | "none";

export type InsightContentBlock =
  | { type: "paragraph"; text: string }
  | { type: "h2"; text: string; id?: string }
  | { type: "h3"; text: string; id?: string }
  | { type: "ordered-list" | "unordered-list"; items: string[] }
  | { type: "blockquote"; text: string; cite?: string }
  | { type: "image"; src: string; alt: string; caption?: string; width?: number; height?: number }
  | { type: "table"; headers: string[]; rows: string[][]; caption?: string }
  | { type: "callout"; heading?: string; text: string }
  | { type: "link"; text: string; href: string }
  | { type: "button"; label: string; href: string }
  | { type: "code"; code: string; language?: string }
  | { type: "related-service"; serviceSlug: string; label?: string }
  | { type: "inline-cta" };

export type Insight = {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  category: InsightCategory;
  publishedAt?: string;
  updatedAt?: string;
  author: "Nicole Buloran" | "Nick Castillo" | "Fractionl Studio";
  readingTime: string;
  heroImage?: string;
  heroImageAlt?: string;
  heroImageWidth?: number;
  heroImageHeight?: number;
  featured: boolean;
  status: InsightStatus;
  seoTitle: string;
  metaDescription: string;
  canonicalUrl?: string;
  targetKeywords: string[];
  content: InsightContentBlock[];
  relatedServiceSlugs: string[];
  relatedInsightSlugs: string[];
  ctaVariant: InsightCtaVariant;
  ctaContent?: {
    eyebrow: string;
    heading: string;
    body: string;
    label: string;
    href: string;
  };
};

export function calculateReadingTime(content: InsightContentBlock[]) {
  const words = content.flatMap((block) => {
    if ("text" in block) return block.text;
    if ("items" in block) return block.items.join(" ");
    if (block.type === "table") return [...block.headers, ...block.rows.flat()].join(" ");
    if (block.type === "code") return block.code;
    return "";
  }).join(" ").trim().split(/\s+/).filter(Boolean).length;

  return `${Math.max(1, Math.ceil(words / 200))} min read`;
}

const websiteMaintenanceContent: InsightContentBlock[] = [
  { type: "paragraph", text: "You launched your website, it looked great on day one, and then... life happened. Clients, projects, hiring — the site got pushed to the back burner. If that sounds familiar, you're not alone. Most business owners treat their website like a one-time purchase instead of an ongoing asset, and that's where things start to quietly go wrong." },
  { type: "paragraph", text: "This guide breaks down what website maintenance actually involves, whether you really need it, and what it tends to cost — so you can make an informed call instead of guessing." },
  { type: "h2", text: "Do Websites Need Maintenance?" },
  { type: "paragraph", text: "Short answer: yes, every website does, the same way every vehicle needs oil changes regardless of how well it was built." },
  { type: "paragraph", text: "A website isn't a static brochure — it's built on software (a CMS like WordPress, plugins, themes, hosting infrastructure) that's constantly being updated by developers around the world. When those underlying pieces update and your site doesn't keep pace, you start accumulating risk: security vulnerabilities, broken functionality, slow load times, and compatibility issues with browsers or devices." },
  { type: "paragraph", text: "A few signs your site is overdue for attention:" },
  { type: "unordered-list", items: [
    "Pages load noticeably slower than they used to",
    "You've gotten a security warning or “not secure” flag in the browser",
    "Contact forms stop sending emails and nobody noticed for weeks",
    "Plugins or themes haven't been updated in over a year",
    "You don't actually know who has admin access to your own site",
  ] },
  { type: "paragraph", text: "None of these show up on the homepage. That's exactly why maintenance gets neglected — the problems are invisible until they're expensive." },
  { type: "h2", text: "What Website Maintenance Actually Includes" },
  { type: "paragraph", text: "“Maintenance” gets used as a catch-all term, so it helps to know what's typically bundled into it:" },
  { type: "h3", text: "Core and plugin updates" },
  { type: "paragraph", text: "CMS platforms, plugins, and themes release updates regularly — often for security patches, not just new features. Skipping these is the single biggest cause of hacked small business websites." },
  { type: "h3", text: "Backups" },
  { type: "paragraph", text: "Regular, tested backups mean that if something does break — a bad update, a hack, human error — you can roll back instead of starting from scratch." },
  { type: "h3", text: "Security monitoring" },
  { type: "paragraph", text: "Malware scanning, firewall rules, and uptime monitoring catch problems before a customer does." },
  { type: "h3", text: "Website updates" },
  { type: "paragraph", text: "This is the content side: swapping out old promotions, updating staff bios and pricing, adding new pages, refreshing images, fixing typos. A site that hasn't changed in two years tells visitors (and Google) that the business might be stagnant too." },
  { type: "h3", text: "Performance checks" },
  { type: "paragraph", text: "Page speed directly affects both user experience and search rankings. Maintenance includes catching what's slowing the site down — unoptimized images, bloated plugins, outdated code." },
  { type: "h3", text: "Website support" },
  { type: "paragraph", text: "This is the human layer — having someone to call when a form breaks, a page goes down, or you just need a small change made without learning to code." },
  { type: "paragraph", text: "Some of this can be automated. A lot of it still needs a person who actually understands your site to review what the automation flags and act on it." },
  { type: "h2", text: "What Happens If You Skip It" },
  { type: "paragraph", text: "The risk isn't always dramatic. Sometimes it's a slow bleed: search rankings drift down because the site got slower, a contact form quietly stopped working three months ago, or a plugin conflict makes the checkout page glitch on mobile. Other times it's sudden — a site gets hacked, defaced, or used to redirect visitors to spam, and now you're looking at emergency cleanup instead of a routine update." },
  { type: "paragraph", text: "Either way, the fix almost always costs more than the prevention would have. Recovering a hacked WordPress site, restoring from a bad backup (or not having one), or rebuilding lost SEO rankings takes real time and real money — far more than staying current would have." },
  { type: "h2", text: "Website Maintenance Cost: What to Expect" },
  { type: "paragraph", text: "Pricing varies a lot depending on the size of the site, the platform it's built on, and how much hands-on support you want. As a general guide:" },
  { type: "unordered-list", items: [
    "Basic plans (updates, backups, uptime monitoring) often run in the range of $50–150/month for a small business site",
    "Mid-tier plans (the above plus security monitoring, performance optimization, and a small monthly bank of content updates) often land around $150–400/month",
    "Higher-touch retainers (frequent content changes, priority support, ongoing optimization) can run $400+/month, especially for larger or e-commerce sites",
  ] },
  { type: "paragraph", text: "These are general industry ranges, not a quote — actual pricing depends on your site's complexity and what's included. The honest comparison to make isn't “maintenance cost vs. $0,” it's “maintenance cost vs. the cost of a rebuild, a hack cleanup, or months of lost leads from a broken contact form.”" },
  { type: "h2", text: "DIY vs. Website Maintenance Services" },
  { type: "paragraph", text: "Some business owners handle basic updates themselves, and for very simple sites, that can work — if you actually have the time and consistency to do it monthly, not just when something breaks." },
  { type: "paragraph", text: "Where it tends to fall apart is during busy seasons (which, conveniently, is also when your website matters most) or when something technical goes wrong and you don't have the background to diagnose it. That's usually the point where business owners look for website maintenance services instead — not because they can't learn it, but because their time is better spent running the business." },
  { type: "paragraph", text: "A good maintenance partner should be doing more than pushing update buttons. They should know your site's history, flag issues before they become emergencies, and be reachable when something needs fixing now, not next week." },
  { type: "inline-cta" },
  { type: "h2", text: "Frequently Asked Questions" },
  { type: "h3", text: "Do all websites need maintenance?" },
  { type: "paragraph", text: "Yes. Every website runs on software — a CMS, plugins, themes, hosting — that updates constantly. Without regular maintenance, sites accumulate security vulnerabilities and performance issues over time." },
  { type: "h3", text: "How much does website maintenance cost?" },
  { type: "paragraph", text: "Basic plans typically range from $50–150/month, mid-tier plans $150–400/month, and higher-touch retainers $400+/month, depending on site size and the level of support included." },
  { type: "h3", text: "What's included in website maintenance services?" },
  { type: "paragraph", text: "Core and plugin updates, backups, security monitoring, performance checks, and content updates such as text, images, pricing, and new pages, plus ongoing support when something breaks." },
  { type: "h3", text: "How often should a website be updated?" },
  { type: "paragraph", text: "Security and plugin updates should be checked monthly at minimum. Content updates like pricing, promotions, and staff info should happen as soon as something changes in the business." },
  { type: "h2", text: "The Bottom Line" },
  { type: "paragraph", text: "A website isn't something you finish — it's something you maintain, the same way you maintain your storefront, your equipment, or your books. The businesses that treat it that way tend to avoid the expensive surprises: the hack that takes a week to clean up, the broken form that quietly cost a month of leads, the redesign that becomes a full rebuild because nothing was kept current." },
  { type: "paragraph", text: "If you're not sure where your site currently stands — whether it's been updated recently, how secure it is, or what it would take to get it on a proper maintenance plan — that's a quick conversation, not a big project." },
  { type: "link", text: "Take a look at our website maintenance and support services", href: "/services/managed-hosting-support" },
  { type: "paragraph", text: "See what's involved, or reach out and we'll take a look at your site together." },
];

const websiteTimelineContent: InsightContentBlock[] = [
  { type: "paragraph", text: "How long does it take to build a website? is one of the first questions almost every client asks us — and it’s a fair one. You’re trying to plan a launch, coordinate marketing, or just figure out when you can stop dreading your current site. The honest answer is: it depends on scope, but most custom websites take anywhere from 4 to 12 weeks from kickoff to launch. Anyone promising a polished, custom site in 48 hours is either templating something generic or skipping steps you’ll pay for later." },
  { type: "paragraph", text: "Here’s a realistic breakdown of the website development timeline, stage by stage, so you know what to actually expect." },
  { type: "h2", text: "What Affects Your Website Timeline" },
  { type: "paragraph", text: "Before getting into the week-by-week breakdown, it helps to know what actually moves the needle on timing:" },
  { type: "unordered-list", items: [
    "Site size — A 5-page brochure site moves much faster than a 20-page site with blog, resources, and service pages for every location.",
    "Custom design vs. template — Custom design takes longer than a templated build, but it’s the difference between a site that looks like everyone else’s and one that actually represents your brand.",
    "Functionality — A basic site is simple. CRM integrations, booking systems, membership areas, or custom databases add real time to the build.",
    "Content readiness — This is the single biggest factor we see in practice. If your copy, photos, and branding are ready on day one, you’ll move fast. If we’re waiting on content, the project stalls — not because of design or development, but because there’s nothing to put on the page yet.",
    "Number of stakeholders — One decision-maker reviewing and approving moves faster than a five-person committee.",
    "Revisions — Every round of feedback is healthy and expected, but each round also adds time, so being decisive during reviews keeps things moving.",
  ] },
  { type: "h2", text: "The Website Design Process, Stage by Stage" },
  { type: "h3", text: "1. Discovery & Strategy (1–2 weeks)" },
  { type: "paragraph", text: "This is where we figure out what we’re actually building before anyone touches a design file. We dig into your business goals, your audience, your competitors, and what’s not working on your current site (if you have one). For a redesign, this stage also includes auditing your existing content and structure to decide what to keep, what to cut, and what’s missing entirely." },
  { type: "h3", text: "2. Sitemap & Content Strategy (3–5 days)" },
  { type: "paragraph", text: "We map out the pages, navigation, and structure of the site before any visual design starts. This is also when content needs start to get nailed down — what copy exists, what needs writing, what images or assets are needed. Getting this right early prevents expensive restructuring later." },
  { type: "h3", text: "3. Design (2–3 weeks)" },
  { type: "paragraph", text: "This is where your brand comes to life — homepage concepts, key page layouts, and the overall visual direction. We typically share initial concepts, gather feedback, and refine through one or two rounds before moving to development. This stage moves fastest when feedback is specific and decisions get made quickly rather than sitting in inboxes." },
  { type: "h3", text: "4. Development (2–4 weeks)" },
  { type: "paragraph", text: "Once design is approved, the site gets built — whether that’s a custom WordPress build, a headless setup, or integrations with tools like a CRM (we recently built one into a client’s site to connect their lead forms directly to their sales pipeline). This stage runs in parallel with final content population, so the more content that’s ready going in, the smoother it goes." },
  { type: "h3", text: "5. Testing & QA (3–5 days)" },
  { type: "paragraph", text: "Cross-browser checks, mobile responsiveness, broken link checks, form testing, page speed — this is the unglamorous stage that keeps your site from breaking the week after launch." },
  { type: "h3", text: "6. Launch & Handoff (2–3 days)" },
  { type: "paragraph", text: "DNS, hosting setup, final go-live, and a walkthrough so you actually know how to update your own site afterward. A good launch includes training, not just a handoff email." },
  { type: "paragraph", text: "Total realistic timeline: 6–10 weeks for most small business websites. Larger or more complex builds (think multi-location healthcare platforms or sites with custom onboarding flows) can run 10–14 weeks." },
  { type: "h2", text: "How Long Does It Take to Redesign a Website?" },
  { type: "paragraph", text: "Redesigns are often assumed to be faster than new builds, but in practice they can take just as long — sometimes longer. You’re not just designing; you’re auditing what exists, deciding what content survives the move, untangling old structure, and often migrating data or integrations from the old site. A redesign of an established business site typically lands in the same 6–10 week range as a new build, with the discovery and content audit phase usually taking longer than it would for a brand-new site." },
  { type: "h2", text: "How to Keep Your Website Project on Schedule" },
  { type: "paragraph", text: "The studios that hit their timelines and the ones that don’t usually differ on the same few things:" },
  { type: "unordered-list", items: [
    "Have your content ready before kickoff — or at least a realistic plan for when it’ll be ready.",
    "Designate one decision-maker for feedback and approvals, even if others weigh in informally.",
    "Turn around feedback within 48 hours during review stages — delays compound fast.",
    "Be upfront about integrations early — CRM connections, booking tools, or custom functionality should be flagged in discovery, not discovered in week 6.",
    "Trust the process order — strategy before design, design before development. Skipping ahead almost always costs more time than it saves.",
  ] },
  { type: "inline-cta" },
  { type: "h2", text: "The Bottom Line" },
  { type: "paragraph", text: "A custom website realistically takes 6–10 weeks from kickoff to launch, with content readiness being the biggest factor in whether you hit that window or run past it. If someone’s quoting you a custom site in a week, ask what’s actually getting built — and if someone’s quoting you four months for a five-page site, ask why." },
  { type: "paragraph", text: "If you’re planning a new site or a redesign and want a timeline specific to your project, get in touch with Fractionl Studio — we’ll walk you through exactly what your build would look like, start to finish." },
  { type: "h2", text: "Frequently Asked Questions" },
  { type: "h3", text: "How long does it take to build a website?" },
  { type: "paragraph", text: "Most custom websites take 6–10 weeks from kickoff to launch, depending on site size, functionality, and how quickly content and feedback are provided." },
  { type: "h3", text: "What’s the fastest a website can realistically be built?" },
  { type: "paragraph", text: "A simple brochure site with content ready on day one can launch in as little as 3–4 weeks. Anything custom-designed and fully tested rarely moves faster than that without cutting corners." },
  { type: "h3", text: "How long does it take to redesign a website?" },
  { type: "paragraph", text: "Redesigns typically take the same 6–10 weeks as a new build, sometimes longer, since they involve auditing existing content, structure, and integrations before any new design work starts." },
  { type: "h3", text: "What’s the biggest factor that slows down a website timeline?" },
  { type: "paragraph", text: "Content readiness. Design and development can move quickly, but projects stall when copy, photos, or branding assets aren’t ready when needed." },
  { type: "h3", text: "How long does the design phase of a website take?" },
  { type: "paragraph", text: "Design typically takes 2–3 weeks, covering homepage concepts, key page layouts, and one or two rounds of feedback before development begins." },
];

const websiteCostingCustomersContent: InsightContentBlock[] = [
  { type: "paragraph", text: "Your website is supposed to be your hardest-working employee — open 24/7, making the case for your business before a prospect ever picks up the phone. But an outdated website doesn't just sit there quietly underperforming. It actively pushes people away, often without you realizing it's happening." },
  { type: "paragraph", text: "If you've had a nagging feeling that your site isn't pulling its weight, here are 10 signs your website needs a redesign — and what to do about it." },
  { type: "h2", text: "1. It Looks Outdated" },
  { type: "paragraph", text: "Visitors form an opinion about your business within seconds of landing on your site, and most of that judgment is visual. Dated fonts, clip-art-style graphics, cramped layouts, or a design that screams “early 2010s” all signal one thing to a visitor: if the website hasn't been updated, maybe the business hasn't either. That's a tough first impression to recover from, especially against competitors with a more current look." },
  { type: "h2", text: "2. It's Not Mobile-Friendly" },
  { type: "paragraph", text: "More than half of web traffic now comes from phones. If your site requires pinching, zooming, or sideways scrolling to read on a mobile screen, you're frustrating the majority of the people who land on it. Google also factors mobile usability into search rankings, so a clunky mobile experience can hurt you twice — once with visitors, and once with your visibility in search results." },
  { type: "h2", text: "3. It Loads Too Slowly" },
  { type: "paragraph", text: "Every extra second of load time increases the odds that a visitor bounces before the page even finishes loading. A slow site is one of the most common — and most fixable — website conversion problems out there. It's often caused by bloated images, outdated code, or a hosting setup that hasn't kept pace with the site's content." },
  { type: "h2", text: "4. Visitors Don't Know What to Do Next" },
  { type: "paragraph", text: "Take a hard look at your homepage. Is it obvious what action you want a visitor to take — book a call, request a quote, make a purchase? If there's no clear call to action, or there are too many competing ones, people will leave without doing anything at all. A confused visitor doesn't convert; they close the tab." },
  { type: "h2", text: "5. The Navigation Is Confusing" },
  { type: "paragraph", text: "If someone has to hunt for basic information — your services, your pricing, your contact details — they'll often give up and go to a competitor instead. Confusing menus, buried pages, and inconsistent labeling are classic business website mistakes that quietly chip away at your conversion rate." },
  { type: "h2", text: "6. Your Branding Feels Inconsistent" },
  { type: "paragraph", text: "Mismatched fonts, colors that don't match your logo, or a tone that swings from formal to casual page to page all undermine trust. A website should feel like a cohesive extension of your brand, not a patchwork of decisions made at different points over the years." },
  { type: "h2", text: "7. It Doesn't Reflect What You Actually Do Now" },
  { type: "paragraph", text: "Businesses evolve — services get added, dropped, or repositioned — but websites often don't keep up. If your site is still describing a version of your business from three years ago, you're either confusing potential customers or losing the work you're best positioned to win today." },
  { type: "h2", text: "8. There's No Social Proof" },
  { type: "paragraph", text: "Testimonials, case studies, client logos, reviews — these are some of the most persuasive elements on a website, and a surprising number of sites leave them out entirely. Without proof that real people have had a good experience with you, visitors are left to take your word for it, and most won't." },
  { type: "inline-cta" },
  { type: "h2", text: "9. It's Not Built to Rank" },
  { type: "paragraph", text: "An outdated website is often an under-optimized one. Missing page titles, no meta descriptions, slow load times, and a lack of fresh content all make it harder for search engines to find and rank your site. If you're invisible in search results, it doesn't matter how good the website looks once someone finally lands on it." },
  { type: "h2", text: "10. You're Embarrassed to Share the Link" },
  { type: "paragraph", text: "This one is more gut check than checklist item: if you hesitate before sending someone to your website, that hesitation is telling you something. Your site should be something you're proud to put in front of a prospective client, not something you quietly hope they don't look at too closely." },
  { type: "h2", text: "When to Redesign a Website" },
  { type: "paragraph", text: "You don't need to check every box above to justify a redesign. As a general rule, it's time to consider one if:" },
  { type: "unordered-list", items: ["It's been more than 3–4 years since your last redesign", "You've noticed a drop in inquiries, leads, or sales tied to your site", "Your business has changed significantly since the site was built", "You're consistently fielding the same confused questions from prospects that your website should be answering"] },
  { type: "paragraph", text: "A website redesign isn't just a cosmetic refresh — done well, it directly addresses the conversion problems above and turns your site back into an asset instead of a liability." },
  { type: "h2", text: "Ready to Fix What's Costing You Customers?" },
  { type: "paragraph", text: "At Fractionl Studio, we specialize in redesigning websites for small and growing businesses — combining clean, modern design with development that actually performs. If any of the signs above sound familiar, it's worth a conversation." },
  { type: "link", text: "Check out our services to see how we can help", href: "/services" },
  { type: "paragraph", text: "Or get in touch to talk through what a redesign could look like for your business." },
  { type: "h2", text: "Frequently Asked Questions" },
  { type: "h3", text: "How do I know if my website needs a redesign?" },
  { type: "paragraph", text: "Common signs include an outdated look, slow load times, poor mobile experience, confusing navigation, no clear calls to action, and a drop in leads or inquiries coming from your site." },
  { type: "h3", text: "How often should a business website be redesigned?" },
  { type: "paragraph", text: "Most businesses should consider a redesign every 3 to 4 years, or sooner if the business itself has changed significantly or the site is underperforming." },
  { type: "h3", text: "Can a bad website really cost me customers?" },
  { type: "paragraph", text: "Yes. A slow, outdated, or confusing website increases bounce rates and reduces conversions, meaning visitors leave before taking any action like contacting you or making a purchase." },
  { type: "h3", text: "When should I hire a web designer?" },
  { type: "paragraph", text: "It's time to hire a web designer when your current site no longer reflects your business, isn't generating leads, looks outdated compared to competitors, or performs poorly on mobile devices." },
];

const choosingWebDesignerContent: InsightContentBlock[] = [
  { type: "paragraph", text: "Your website is often the first impression a potential client gets of your business — before they call, before they walk in, before they ever shake your hand. So it makes sense that choosing the right person (or team) to build it shouldn't be a rushed decision. If you've started Googling \"how to choose a web designer\" and come up with more questions than answers, this guide will walk you through exactly what to look for." },
  { type: "h2", text: "Start With What Your Business Actually Needs" },
  { type: "paragraph", text: "Before you even start hiring a web designer, get clear on the basics: What is this site supposed to do? A restaurant needs an easy-to-update menu and online reservations. A clinic needs a clean intake form and HIPAA-conscious patient communication. A service business needs a clear path from \"I found you\" to \"I booked you.\"" },
  { type: "paragraph", text: "Knowing this upfront helps you filter out designers who aren't a fit before you waste time on calls that go nowhere." },
  { type: "h2", text: "What Makes Someone the \"Best Web Designer\" for Your Business" },
  { type: "paragraph", text: "There's no universal best web designer — there's only the best fit for your goals, budget, and timeline. That said, a few things separate solid professionals from risky hires:" },
  { type: "h3", text: "A portfolio with real, working sites" },
  { type: "paragraph", text: "Not just polished screenshots — actual live URLs you can click through on your phone and laptop. Look for variety that's still relevant to your industry or business size, not just one flashy example repeated in different colors." },
  { type: "h3", text: "Design and development competence" },
  { type: "paragraph", text: "A beautiful design that breaks the moment it's coded, or loads slowly, or isn't mobile-responsive, isn't actually a good website. Ask whether the same person or team handles both design and build, or whether it's handed off — handoffs are where quality often gets lost." },
  { type: "h3", text: "Clear, two-way communication" },
  { type: "paragraph", text: "During your first conversation, notice whether they're asking about your business goals or just talking about themselves. The good ones ask more questions than they answer in a first call." },
  { type: "h3", text: "Transparent process and pricing" },
  { type: "paragraph", text: "Vague answers about cost, timeline, or what's included are a red flag. You should walk away from an initial conversation with a rough sense of investment and next steps, not just a \"let's chat more.\"" },
  { type: "h2", text: "Questions to Ask a Web Designer Before You Hire" },
  { type: "paragraph", text: "Bring this list to your first call or email exchange — the answers (or lack of them) will tell you a lot." },
  { type: "ordered-list", items: [
    "Can I see live examples of sites you've built, not just designed?",
    "Will I own the website, domain, and code once it's finished?",
    "What platform will the site be built on, and can I update it myself afterward?",
    "What's included in the price — revisions, copywriting, SEO basics, mobile optimization?",
    "What's your typical timeline from kickoff to launch?",
    "Who do I contact if something breaks after the site goes live?",
    "Do you offer ongoing maintenance, or is this a one-time build?",
    "Have you worked with businesses in my industry before?",
  ] },
  { type: "paragraph", text: "If a designer gets cagey or vague on any of these, treat it as useful information." },
  { type: "h2", text: "Freelancer vs. Choosing a Web Design Agency" },
  { type: "paragraph", text: "Both paths can work — it depends on what you need." },
  { type: "h3", text: "A freelancer" },
  { type: "paragraph", text: "A freelancer is often more affordable and gives you a direct line to the person doing the work. The risk: if they get busy, sick, or move on to other projects, your timeline (and support afterward) can suffer." },
  { type: "h3", text: "An agency or small studio" },
  { type: "paragraph", text: "An agency or small studio typically offers more reliability — there's a team behind the work, not just one person's bandwidth. Look for studios that are full-service, meaning they handle both design and development under one roof, so you're not stuck managing two vendors and pointing fingers when something doesn't line up." },
  { type: "paragraph", text: "When you're choosing a web design agency, ask the same questions you'd ask a freelancer, plus: Who specifically will be working on my project, and will I have direct access to them, or just a project manager?" },
  { type: "inline-cta" },
  { type: "h2", text: "Watch Out for These Red Flags" },
  { type: "unordered-list", items: [
    "Pressure to sign before you've seen real examples of their work",
    "No clear answer on who owns the site and code after launch",
    "Pricing that seems \"too good to be true\" with no explanation of what's excluded",
    "Portfolios full of template-based sites that all look the same",
    "No mention of mobile responsiveness, page speed, or basic SEO",
  ] },
  { type: "h2", text: "Bringing It All Together" },
  { type: "paragraph", text: "Choosing the right web designer comes down to three things: a portfolio that proves they can actually build (not just design), clear communication from the first conversation, and honest answers to direct questions about ownership, pricing, and support. Take your time, ask the questions above, and don't be afraid to walk away from anyone who can't answer them clearly." },
  { type: "paragraph", text: "If you're currently comparing options, Nicole Design & Co. is a full-service design and development studio — meaning the same team handles your design and the build, so nothing gets lost in translation." },
  { type: "link", text: "You can see our process and what's included at nicoledesignandco.com/services.", href: "https://nicoledesignandco.com/services" },
];

const buildOrHireContent: InsightContentBlock[] = [
  { type: "paragraph", text: "If you've typed \"should I build my own website\" into Google, you're probably staring at three tabs right now: Wix, Squarespace, and some AI website builder promising a \"stunning site in minutes.\" All three are tempting. All three are also selling you something — speed and cheapness, not necessarily results." },
  { type: "paragraph", text: "Here's the honest answer: it depends on what your website actually needs to do for your business. Let's break down DIY website vs professional so you can make the call with your eyes open." },
  { type: "h2", text: "What DIY Builders Actually Get You Right" },
  { type: "paragraph", text: "Wix, Squarespace, and the new wave of AI website builders aren't bad products. For a hobby blog, a single-page portfolio, or a \"we exist, here's our phone number\" placeholder, they're genuinely fine. You get:" },
  { type: "unordered-list", items: [
    "A live site in a day, sometimes hours",
    "No coding required",
    "Built-in hosting, so you're not managing servers",
    "A monthly cost instead of a big upfront one",
  ] },
  { type: "paragraph", text: "If your business doesn't depend on the website to generate leads, sell products, or convert visitors into customers, this might be all you need. No judgment — not every business needs a $5,000 website." },
  { type: "h2", text: "Where the DIY Route Quietly Costs You More" },
  { type: "paragraph", text: "The problem isn't that Wix vs web designer is a fair fight on price. It's that the comparison usually stops at \"how much does it cost to launch\" and ignores \"how much does it cost to run.\"" },
  { type: "h3", text: "Template Limitations Compound Over Time" },
  { type: "paragraph", text: "Every other business on the same template plan looks like you. Customizing past a certain point on Wix or Squarespace means fighting the platform, not building with it." },
  { type: "h3", text: "You Become the Web Developer" },
  { type: "paragraph", text: "Updating copy is easy. Restructuring a page, fixing a broken integration, or making the site work properly on mobile after a redesign is not. That's time pulled directly from running your actual business." },
  { type: "h3", text: "SEO Is Harder to Get Right" },
  { type: "paragraph", text: "Builder platforms have improved here, but page speed, clean code structure, and technical SEO still tend to lag behind a custom-built site — and search rankings are exactly where most small businesses need the help." },
  { type: "h3", text: "AI Website Builders Add a New Wrinkle" },
  { type: "paragraph", text: "The AI website builder vs designer comparison is getting more common, and AI tools are fast for a first draft. But they're trained on patterns, not your business. They don't know that your psychology practice needs a HIPAA-conscious contact form, or that your restaurant's online ordering needs to talk to your POS system. They generate something — they don't solve your specific problem." },
  { type: "h2", text: "What Hiring a Professional Actually Buys You" },
  { type: "paragraph", text: "This is the part DIY comparisons usually skip: a professional isn't just building you a site, they're solving a business problem." },
  { type: "paragraph", text: "When we take on a project — whether it's a full redesign for a hospitality client, a CRM integration so leads stop falling through cracks, or a multi-screen onboarding flow for a healthcare platform — the work isn't \"make it pretty.\" It's:" },
  { type: "unordered-list", items: [
    "Strategy first. What is this page supposed to do, and for whom?",
    "Custom structure, not a template stretched to fit your business",
    "Integrations that actually work — booking systems, CRMs, payment processors, the unglamorous plumbing that makes a site useful instead of decorative",
    "A site that's actually yours when you outgrow the original scope, instead of being boxed in by what the platform allows",
  ] },
  { type: "paragraph", text: "A Squarespace vs professional website comparison usually centers on the wrong question — \"which is prettier\" — when the real question is \"which one is actually going to convert visitors and grow with the business.\"" },
  { type: "h2", text: "So, Should You Build Your Own Website?" },
  { type: "paragraph", text: "Honestly ask yourself these questions:" },
  { type: "unordered-list", items: [
    "Does my website need to make money, directly or indirectly (leads, bookings, sales)? If yes, lean professional.",
    "Do I have unique workflows — booking, inventory, CRM, industry-specific compliance — that a generic builder won't handle out of the box? If yes, lean professional.",
    "Is this a temporary or low-stakes site (a personal project, a quick placeholder while something bigger gets planned)? If yes, DIY is a reasonable bridge.",
    "Do I have the time to be my own web developer for the life of this site? If the honest answer is no, that's worth pricing into your decision — your time isn't free either.",
  ] },
  { type: "paragraph", text: "There's no universal right answer, but there is a right answer for your business — and it usually comes down to whether the website is a brochure or a business tool." },
  { type: "inline-cta" },
  { type: "h2", text: "When It's Time to Hire a Web Designer" },
  { type: "paragraph", text: "If you've outgrown your builder site, or you're starting from scratch and know the site needs to actually perform — not just exist — that's the point to bring in a professional. A good studio will tell you honestly if a builder is genuinely fine for what you need, instead of upselling you on something bigger than your business requires." },
  { type: "paragraph", text: "We do exactly this kind of work at Fractionl Studio — full-service design through development, including the technical integrations that DIY platforms struggle with. If you want a second opinion on whether your project needs a custom build or whether a builder will actually serve you fine, take a look at our services or get in touch." },
  { type: "link", text: "Explore Fractionl Studio services", href: "/services" },
];

const websiteHostingExplainedContent: InsightContentBlock[] = [
  { type: "paragraph", text: "If you've ever started building a website and hit a screen asking you to \"choose a hosting plan,\" you've probably had a moment of pure confusion. Shared hosting? VPS? Managed WordPress? Cloud hosting? It can feel like you need a computer science degree just to get your business online." },
  { type: "paragraph", text: "Here's the good news: you don't. This guide breaks down website hosting explained in plain English, so you can make a confident decision and get back to running your business." },
  { type: "h2", text: "What Is Website Hosting?" },
  { type: "paragraph", text: "At its simplest, website hosting is the service that stores your website's files — your pages, images, code, everything — on a server (a powerful computer connected to the internet 24/7) so people can visit your site any time, from anywhere." },
  { type: "paragraph", text: "Think of it like renting space for a storefront. Your domain name (like fractionlstudio.com) is your street address. Your hosting is the actual building where your \"store\" lives. Without hosting, you have an address but no building — visitors have nowhere to go." },
  { type: "paragraph", text: "When someone types your web address into their browser, their computer sends a request to your hosting server, which then sends back all the files needed to display your site. The speed, reliability, and security of that exchange depends entirely on the quality of your hosting." },
  { type: "h2", text: "Do I Need Website Hosting?" },
  { type: "paragraph", text: "Short answer: yes, if you want a website that's actually live on the internet." },
  { type: "paragraph", text: "Some all-in-one platforms (like Squarespace or Wix) bundle hosting into their subscription, so you may already have it without realizing it. But if you're building a custom site, using WordPress, or working with a designer or developer, you'll need to choose and pay for hosting separately — and that choice matters more than most business owners expect." },
  { type: "paragraph", text: "A few signs hosting deserves real attention rather than an afterthought:" },
  { type: "unordered-list", items: [
    "Your site needs to load quickly, especially on mobile, where slow load times directly hurt conversions and search rankings.",
    "You're collecting customer information, bookings, or payments, which means security can't be an afterthought.",
    "You expect your traffic to grow, and you don't want to migrate everything later because you outgrew a budget plan.",
    "You don't have technical staff in-house, so you need a setup that's reliable without requiring constant babysitting.",
  ] },
  { type: "h2", text: "Types of Website Hosting (Explained Simply)" },
  { type: "paragraph", text: "There's no single \"best\" hosting type — it depends on your business size, technical comfort, and budget. Here's a quick breakdown:" },
  { type: "table", headers: ["Hosting type", "How it works", "Considerations"], rows: [
    ["Shared hosting", "Your site lives on a server alongside many other websites, splitting the cost and the server's resources among everyone.", "It's the most affordable option and fine for a simple brochure-style site, but performance can dip if a neighbouring site gets a traffic spike."],
    ["VPS (Virtual Private Server) hosting", "You still share a physical server, but your slice of it is walled off with dedicated resources.", "More power and stability than shared hosting, at a moderate price increase."],
    ["Dedicated hosting", "You get an entire server to yourself.", "Maximum control and performance, but it's costly and usually overkill unless you're running a high-traffic platform or app."],
    ["Cloud hosting", "Your site runs across a network of connected servers instead of just one. If traffic spikes, the load balances automatically.", "This has become a popular middle ground for growing small businesses because it scales with you."],
    ["Managed WordPress hosting", "Built specifically for WordPress sites, with automatic updates, backups, and security handled for you.", "A strong choice if your site runs on WordPress and you'd rather not manage server-level details yourself."],
  ], caption: "A plain-language comparison of the hosting types covered in this guide." },
  { type: "h2", text: "Website Hosting for Small Business: What Actually Matters" },
  { type: "paragraph", text: "Large enterprises think about hosting in terms of server architecture and IT teams. Small business owners need to think about it differently — in terms of outcomes." },
  { type: "paragraph", text: "When you're evaluating website hosting for small business use, here's what actually moves the needle:" },
  { type: "h3", text: "Uptime" },
  { type: "paragraph", text: "This is the percentage of time your site is live and accessible. Look for guarantees of 99.9% or higher. Every hour your site is down is an hour customers can't find you, book with you, or buy from you." },
  { type: "h3", text: "Page speed" },
  { type: "paragraph", text: "Slow sites lose visitors and rank lower in search results. Good hosting (paired with good site setup) keeps load times under a few seconds." },
  { type: "h3", text: "Security" },
  { type: "paragraph", text: "SSL certificates, malware scanning, and regular backups should be standard, not an upsell. This matters even more if you're collecting customer data or running e-commerce." },
  { type: "h3", text: "Support" },
  { type: "paragraph", text: "When something breaks at 11pm before a big launch, you want a real person to talk to, not a ticket queue that takes three days to respond." },
  { type: "h3", text: "Room to grow" },
  { type: "paragraph", text: "Choose hosting that can scale as your traffic and needs increase, so you're not migrating your whole site a year from now." },
  { type: "h2", text: "How to Choose the Best Website Hosting for Your Business" },
  { type: "paragraph", text: "There's a lot of marketing noise around \"best website hosting\" lists, and most of them are written to sell affiliate links, not to match hosting to your actual business. Instead of chasing a generic \"best\" list, ask yourself:" },
  { type: "unordered-list", items: [
    "What platform is my site built on? WordPress, a custom-built site, and an e-commerce platform each have different hosting needs.",
    "How much traffic do I realistically expect? A local service business and a growing online store have very different demands.",
    "Do I want to manage technical details, or hand them off? Managed hosting costs more but takes server maintenance off your plate entirely.",
    "What's my budget, both now and as I grow? Cheap hosting that can't scale often costs more in the long run through migrations and downtime.",
  ] },
  { type: "paragraph", text: "If this still feels like a lot to weigh on your own, you're not wrong — and you don't have to figure it out alone." },
  { type: "inline-cta" },
  { type: "h2", text: "Hosting Is Infrastructure. Treat It Like It." },
  { type: "paragraph", text: "It's tempting to treat hosting as a checkbox to get through quickly so you can focus on the \"fun\" parts of your website — design, copy, branding. But hosting is the foundation everything else sits on. A beautifully designed site on unreliable hosting will still load slowly, go down at the worst moments, and frustrate the customers you worked hard to attract." },
  { type: "paragraph", text: "The good news is you don't need to become a hosting expert. You just need a setup that fits your business, configured by someone who's done it before." },
  { type: "h2", text: "Let's Get Your Site Set Up Right" },
  { type: "paragraph", text: "At Fractionl Studio, we handle hosting as part of building and maintaining sites for our clients — so you're not left untangling server settings on your own. Whether you're launching a new site, migrating off a platform you've outgrown, or just want a second opinion on whether your current hosting is actually serving your business, we're happy to talk it through." },
  { type: "paragraph", text: "Check out our services or reach out — we'll help you figure out exactly what your business needs, nothing more and nothing less." },
];

const webDesignerVsDeveloperContent: InsightContentBlock[] = [
  { type: "paragraph", text: "If you've started looking for help with your website, you've probably run into this fork in the road pretty quickly: do you hire a web designer, a web developer, or both? The terms get thrown around so interchangeably that it's easy to assume they're the same job. They're not — and hiring the wrong one (or only half of what you need) is one of the most common reasons small business website projects stall out or end up costing more than planned." },
  { type: "paragraph", text: "Here's a clear breakdown of the difference between a web designer and a web developer, plus how to figure out which one your business actually needs." },
  { type: "h2", text: "What Does a Web Designer Do?" },
  { type: "paragraph", text: "A web designer is responsible for how your website looks, feels, and flows. Think of them as the person shaping the experience: layout, color, typography, imagery, and the overall visual identity of your site. A good designer is also thinking about usability — how a visitor moves from your homepage to a contact form, what draws the eye first, whether your site actually reflects your brand or just looks like a template with your logo dropped in." },
  { type: "h3", text: "Common Things a Web Designer Handles" },
  { type: "unordered-list", items: ["Visual branding and layout for your site", "Wireframes and mockups before anything gets built", "User experience (UX) — making sure the site is easy and intuitive to navigate", "Choosing fonts, colors, and imagery that match your brand", "Designing for mobile and desktop"] },
  { type: "paragraph", text: "What a designer typically does not do: write the code that makes the site actually function. A designer can hand you a beautiful mockup, but someone still has to build it." },
  { type: "h2", text: "What Does a Web Developer Do?" },
  { type: "paragraph", text: "A web developer takes that design (or a set of requirements) and builds the actual, functioning website. This is the technical side — the code, the structure, the systems running behind the scenes. Developers make sure your site works correctly across browsers and devices, loads quickly, and can handle whatever functionality your business needs, whether that's a contact form, an online store, a booking system, or a CRM integration." },
  { type: "h3", text: "Common Things a Web Developer Handles" },
  { type: "unordered-list", items: ["Writing the front-end and back-end code", "Making sure the site is responsive and functions properly", "Integrating tools like CRMs, payment systems, or booking platforms", "Site speed, security, and technical performance", "Ongoing maintenance and updates after launch"] },
  { type: "paragraph", text: "A developer can technically build a site without a designer's input, but the result often looks exactly like what you'd expect from a programmer designing in a vacuum: functional, but not built with your brand or your customer's experience in mind." },
  { type: "h2", text: "Website Designer vs. Developer: The Short Version" },
  { type: "table", caption: "A comparison of the roles described in this article.", headers: ["Comparison", "Web Designer", "Web Developer"], rows: [["Focus", "Look, feel, and user experience", "Code, function, and technical build"], ["Tools", "Figma, Adobe XD, design systems", "HTML/CSS, JavaScript, CMS platforms"], ["Output", "Mockups, wireframes, visual direction", "A working, live website"], ["Good at", "Branding, layout, usability", "Functionality, integrations, performance"]] },
  { type: "paragraph", text: "Neither role replaces the other. A designer without a developer can't launch a site. A developer without a designer can launch one — just not one that necessarily looks like your brand or converts visitors into customers." },
  { type: "h2", text: "So, Do You Need a Web Designer or a Developer?" },
  { type: "paragraph", text: "It depends on where you're starting from and what the project actually requires." },
  { type: "h3", text: "You Probably Need a Designer First If:" },
  { type: "unordered-list", items: ["You have a developer or dev team already, but no clear visual direction", "Your current site works fine technically but doesn't reflect your brand", "You're starting from scratch and need someone to map out the experience before any code gets written"] },
  { type: "h3", text: "You Probably Need a Developer If:" },
  { type: "unordered-list", items: ["You already have designs or brand guidelines and just need them built", "Your site needs specific functionality — a CRM, a booking system, an online store", "Your current site has technical issues (slow load times, broken forms, mobile bugs) but looks fine"] },
  { type: "h3", text: "You Need Both If:" },
  { type: "unordered-list", items: ["You're building a new site from the ground up", "You're rebranding and need the new identity carried through a fully functioning site", "You want a site that looks professional and works reliably, without managing two separate freelancers and hoping their work lines up"] },
  { type: "paragraph", text: "That last scenario is where most small businesses actually land. It's also where things get complicated if you hire a designer and developer separately — handoffs get messy, timelines stretch, and nobody's fully accountable for the end result if something looks off or breaks." },
  { type: "inline-cta" },
  { type: "h2", text: "Website Design and Development, Handled as One Process" },
  { type: "paragraph", text: "This is the gap a full-service studio is built to close. Instead of hiring a designer to create a vision and then crossing your fingers that a separate developer can execute it faithfully, design and development happen as one connected process, with one team accountable for the outcome from first mockup to live site." },
  { type: "paragraph", text: "At Fractionl Studio, that's exactly how we work — design and development under one roof, so your site doesn't just look right, it works right too. If you're trying to figure out which one your project needs, take a look at our services or reach out and we can help you figure out where to start." },
  { type: "link", text: "Explore Fractionl Studio services", href: "/services" },
  { type: "h2", text: "Frequently Asked Questions" },
  { type: "h3", text: "What is the difference between a web designer and a web developer?" },
  { type: "paragraph", text: "A web designer focuses on the look, layout, and user experience of a website. A web developer writes the code that makes the design actually function as a live, working site." },
  { type: "h3", text: "Do I need a web designer or a web developer for my small business website?" },
  { type: "paragraph", text: "Most small businesses need both. A designer shapes how the site looks and feels; a developer builds it so it works correctly across devices and handles any functionality you need, like forms, bookings, or e-commerce." },
  { type: "h3", text: "Can a web developer also do web design?" },
  { type: "paragraph", text: "Some developers have design skills, but design and development are different disciplines. For a polished, brand-aligned result, it's usually better to have a dedicated designer involved, even if one person or team handles both roles." },
  { type: "h3", text: "Is it cheaper to hire one person who does both design and development?" },
  { type: "paragraph", text: "Often, yes. Hiring a single studio or freelancer who handles both reduces handoff issues, miscommunication, and the risk of paying twice to fix mismatched work between separate designers and developers." },
  { type: "h3", text: "How do I know if my website problem is a design issue or a development issue?" },
  { type: "paragraph", text: "If your site looks outdated, confusing, or off-brand, that's a design issue. If it's slow, broken, not mobile-friendly, or missing functionality, that's a development issue. Many small business sites have both, which is why a combined design-and-development approach is often the most efficient fix." },
];

const websiteRedesignChecklistContent: InsightContentBlock[] = [
  { type: "paragraph", text: "Your website is often the first interaction a potential client has with your business. If it's slow, outdated, or hard to navigate, it's quietly costing you leads every single day — whether you notice it or not." },
  { type: "paragraph", text: "So how do you know when \"it's fine for now\" has actually become \"it's holding us back\"? Below is a practical website redesign checklist to help you figure out where your site stands, plus what to do about it." },
  { type: "h2", text: "Why Knowing When to Redesign a Website Matters" },
  { type: "paragraph", text: "A website redesign is a real investment of time, money, and energy, so it shouldn't be a knee-jerk decision. But waiting too long has its own cost: an outdated website can quietly undercut your credibility, your search rankings, and your conversion rate long before anyone tells you it's a problem." },
  { type: "paragraph", text: "The goal of this guide isn't to convince you that you need a redesign right now. It's to give you a clear-eyed way to evaluate your current site so you can make that call with confidence." },
  { type: "h2", text: "The 15-Point Website Redesign Checklist" },
  { type: "h3", text: "1. Your design looks dated compared to competitors" },
  { type: "paragraph", text: "Design trends shift every few years, and visitors notice — even if they can't articulate why. If your site still has stock photo grids, drop shadows everywhere, or a layout that screams \"2014,\" it's signaling something about your business that you probably don't intend." },
  { type: "h3", text: "2. It's not mobile-friendly" },
  { type: "paragraph", text: "More than half of web traffic now comes from mobile devices. If your site isn't fully responsive — buttons too small to tap, text that requires zooming, layouts that break on smaller screens — you're losing visitors before they even get to your content." },
  { type: "h3", text: "3. Page load times are slow" },
  { type: "paragraph", text: "Every extra second of load time increases bounce rate. If your homepage takes more than two or three seconds to load, visitors are leaving before they see what you offer." },
  { type: "h3", text: "4. Your brand has evolved, but your site hasn't" },
  { type: "paragraph", text: "New logo, new messaging, new positioning, new services — and your website still reflects the business you were three years ago? That mismatch confuses visitors and undermines trust." },
  { type: "h3", text: "5. You can't update it yourself" },
  { type: "paragraph", text: "If every small text change or image swap requires calling a developer, your site is working against you instead of for you. A modern site should let you make basic updates without a ticket and a two-week wait." },
  { type: "h3", text: "6. It's not built on a CMS (or you've outgrown the one you have)" },
  { type: "paragraph", text: "Whether it's WordPress, Webflow, or something custom, your site should run on a content management system that fits how your team actually works — not one you've outgrown or never properly learned." },
  { type: "h3", text: "7. Your conversion rate is flat or declining" },
  { type: "paragraph", text: "If traffic is steady but inquiries, bookings, or sales aren't following, the problem is often the site itself — confusing navigation, weak calls to action, or a user journey that doesn't lead anywhere." },
  { type: "h3", text: "8. Your bounce rate is climbing" },
  { type: "paragraph", text: "A high bounce rate is one of the clearest outdated website symptoms there is. It usually means visitors land, don't find what they expected, and leave — fast." },
  { type: "h3", text: "9. Your SEO performance has plateaued" },
  { type: "paragraph", text: "Search algorithms reward sites with solid technical foundations: clean code, fast load times, proper structure, mobile responsiveness. An older site built without modern SEO in mind will keep losing ground no matter how much content you publish." },
  { type: "h3", text: "10. Your site doesn't reflect your actual services" },
  { type: "paragraph", text: "This is one we see constantly with growing businesses: the services list is outdated, key offerings are buried or missing, and the site simply doesn't match what the business does today." },
  { type: "h3", text: "11. There's no clear path to contact or convert" },
  { type: "paragraph", text: "If a first-time visitor has to hunt for a phone number, contact form, or booking link, you're adding unnecessary friction at the exact moment they're ready to act." },
  { type: "h3", text: "12. Your competitors' sites look more credible than yours" },
  { type: "paragraph", text: "Fair or not, people judge businesses by their websites. If a prospect compares you to a competitor with a sharper, more modern site, that comparison can cost you the deal before you ever get a call." },
  { type: "h3", text: "13. You're embarrassed to share your URL" },
  { type: "paragraph", text: "This one's simple but telling: if you hesitate before handing someone your website link, that hesitation is data. Trust it." },
  { type: "h3", text: "14. Your integrations are outdated or missing entirely" },
  { type: "paragraph", text: "No CRM connection, no booking system, no email capture, no analytics worth trusting. A modern business website should connect to the tools you actually use to run your operations." },
  { type: "h3", text: "15. It hasn't been touched in 3+ years" },
  { type: "paragraph", text: "Even a well-built site needs refreshing every few years as design standards, browser behavior, and user expectations shift. If your last redesign predates the pandemic, it's worth a hard look." },
  { type: "h2", text: "How Many Boxes Did You Check?" },
  { type: "unordered-list", items: [
    "1–4: Your site is probably fine with some targeted updates rather than a full rebuild.",
    "5–9: You're due for a redesign in the near future — start planning before it becomes urgent.",
    "10+: Your website is actively working against your business. This should move up your priority list.",
  ] },
  { type: "h2", text: "A Simple Website Redesign Guide: What to Expect" },
  { type: "paragraph", text: "If you've decided it's time, a redesign typically moves through a few clear phases:" },
  { type: "ordered-list", items: [
    "Discovery — understanding your business, your audience, and what the current site is getting wrong.",
    "Strategy and structure — mapping out the site architecture and user journey before any visual design begins.",
    "Design — building a look and feel that reflects where your brand is now.",
    "Development — turning designs into a fast, functional, mobile-friendly site.",
    "Launch and handoff — going live, plus making sure you can actually manage the site afterward.",
  ] },
  { type: "paragraph", text: "A good redesign isn't just a fresh coat of paint. It's a chance to fix the structural and strategic issues that have been quietly working against you." },
  { type: "inline-cta" },
  { type: "h2", text: "Ready to Improve Your Business Website?" },
  { type: "paragraph", text: "If you recognized your site in several of the points above, you don't need to figure out the next step alone. At Fractionl Studio, we work with businesses to redesign websites that actually look credible, load fast, and convert — design through development, end to end." },
  { type: "paragraph", text: "Take a look at our services to see how we can help, or reach out to talk through where your site stands today." },
  { type: "link", text: "Explore Fractionl Studio services", href: "/services" },
];

const greatSmallBusinessWebsiteContent: InsightContentBlock[] = [
  { type: "paragraph", text: "Your website is often the first impression a potential customer has of your business — before they ever walk through your door or pick up the phone. A great small business website does more than look nice. It builds trust, answers questions, and turns visitors into customers." },
  { type: "paragraph", text: "Whether you're launching your first site or rebuilding an outdated one, this business website checklist covers the 12 features every small business website needs to compete in 2026." },
  { type: "h2", text: "1. A Clean, Fast-Loading Design" },
  { type: "paragraph", text: "Visitors decide whether to stay on your site within seconds. A cluttered layout, slow load time, or outdated design sends people straight to a competitor. Following website best practices means prioritizing simplicity: clear navigation, plenty of white space, and pages that load in under three seconds. Speed isn't just about user experience either — search engines factor load time into rankings, so a fast site helps you get found, too." },
  { type: "h2", text: "2. Mobile-Responsive Layout" },
  { type: "paragraph", text: "More than half of all web traffic now comes from phones and tablets. If your site isn't built to resize and reflow on smaller screens, you're losing customers before they even see what you offer. A truly responsive design adjusts images, menus, and text automatically, so the experience feels just as polished on a phone as it does on a desktop." },
  { type: "h2", text: "3. Clear Calls to Action (CTAs)" },
  { type: "paragraph", text: "Every page should answer the question: \"What do I want this visitor to do next?\" Whether it's \"Book a Consultation,\" \"Call Now,\" or \"Get a Free Quote,\" your CTAs should be visible, specific, and repeated throughout the site — not buried in a footer. This is one of the simplest professional website features to implement, and one of the most commonly overlooked." },
  { type: "h2", text: "4. An About Page That Builds Trust" },
  { type: "paragraph", text: "People do business with people, not logos. An About page that shares your story, your team, and your values helps visitors feel confident choosing you over a faceless competitor. For local and service-based businesses especially, this page often gets more traffic than you'd expect — it's where leads go to decide if they trust you." },
  { type: "h2", text: "5. Easy-to-Find Contact Information" },
  { type: "paragraph", text: "Your phone number, email, and physical address (if applicable) should never require a hunt. Place this information in your header or footer on every page, not just a dedicated Contact page. A contact form is helpful, but it shouldn't be the only way to reach you — some customers still prefer to call." },
  { type: "h2", text: "6. Service or Product Pages That Actually Explain What You Do" },
  { type: "paragraph", text: "Vague homepage copy (\"We do it all!\") loses customers. Dedicated pages for each core service or product line — with clear descriptions, pricing guidance where appropriate, and relevant images — help visitors and search engines alike understand exactly what you offer and whether it fits their needs." },
  { type: "h2", text: "7. Social Proof: Reviews and Testimonials" },
  { type: "paragraph", text: "Trust signals matter more online than almost anywhere else, since visitors can't read body language or shake your hand. Star ratings, client testimonials, case studies, and logos of businesses you've worked with all reduce the perceived risk of choosing a small or unfamiliar business over a bigger name." },
  { type: "h2", text: "8. Search Engine Optimization (SEO) Basics" },
  { type: "paragraph", text: "A beautiful site that no one finds isn't doing its job. Website essentials here include proper page titles, meta descriptions, header tags, alt text on images, and a sitemap submitted to Google. SEO isn't a one-time setup — but getting the foundation right from launch makes everything that follows easier." },
  { type: "h2", text: "9. A Blog or Resource Section" },
  { type: "paragraph", text: "Regularly publishing helpful content — like this post — does double duty: it improves your SEO over time by giving search engines fresh, relevant content to index, and it positions you as a knowledgeable, trustworthy choice in your industry. Even a few well-written posts a month can meaningfully move the needle." },
  { type: "h2", text: "10. Security (SSL and Beyond)" },
  { type: "paragraph", text: "An SSL certificate (the padlock icon next to your URL) is non-negotiable in 2026 — without it, browsers actively warn visitors that your site isn't secure, and search engines penalize sites that lack it. Beyond SSL, regular backups and software updates protect you and your customers from data breaches." },
  { type: "h2", text: "11. Integration With the Tools You Already Use" },
  { type: "paragraph", text: "A great business website doesn't operate in isolation. Whether it's a CRM to manage leads, a booking calendar, email marketing software, or payment processing, your site should connect with the systems running your business — not create extra manual work. This is where a lot of \"DIY\" website builders fall short, and where custom development pays off." },
  { type: "h2", text: "12. Easy Content Management" },
  { type: "paragraph", text: "You shouldn't need to call a developer every time you want to update your hours, add a new service, or change a price. A well-built site gives you (or your team) the ability to make simple edits yourself, while still leaving room for a developer to handle bigger changes when needed." },
  { type: "inline-cta" },
  { type: "h2", text: "Putting It All Together" },
  { type: "paragraph", text: "A great small business website isn't about having the flashiest design — it's about combining these business website features into a site that's fast, trustworthy, easy to use, and built to grow with you. Run through this checklist on your current site, and you'll likely spot one or two quick wins, along with a clearer sense of where a bigger refresh might be worth the investment." },
  { type: "paragraph", text: "Not sure where your website stands? At Nicole Design & Co., we help small businesses design and build sites that check every box on this list — from clean design and CRM integration to ongoing support you can actually reach by phone." },
  { type: "link", text: "Take a look at our services", href: "https://nicoledesignandco.com/services" },
  { type: "paragraph", text: "Or get in touch to talk through what your business needs." },
];

// Development-only content for exercising the reusable article template.
// It is deliberately excluded from public lists and marked noindex by the route.
export const insights: Insight[] = [
  {
    id: "what-makes-a-great-small-business-website-12-must-have-features",
    slug: "what-makes-a-great-small-business-website-12-must-have-features",
    title: "What Makes a Great Small Business Website? 12 Must-Have Features",
    excerpt: "Explore 12 essential website features that help small businesses create clarity, build trust, improve usability, and guide customers toward action.",
    category: "Web Design",
    publishedAt: "2026-06-29",
    updatedAt: "2026-06-29",
    author: "Fractionl Studio",
    readingTime: calculateReadingTime(greatSmallBusinessWebsiteContent),
    heroImage: "/images/insights/what-makes-a-great-small-business-website-12-must-have-features/hero.webp",
    heroImageAlt: "Small-business website surrounded by indicators for modern design, mobile usability, speed, SEO, security, accessibility, calls to action, navigation, content, contact information, analytics, and ongoing support.",
    heroImageWidth: 1672,
    heroImageHeight: 941,
    featured: false,
    status: "published",
    seoTitle: "12 Must-Have Features of a Great Small Business Website",
    metaDescription: "Discover 12 essential features every small business website should include to build trust, improve usability, and help customers take action.",
    canonicalUrl: "/insights/what-makes-a-great-small-business-website-12-must-have-features",
    targetKeywords: ["what makes a great small business website", "small business website features", "must-have website features", "small business website checklist", "what should a business website include", "essential website features", "professional small business website", "small business web design", "website features that convert", "business website essentials"],
    relatedServiceSlugs: ["website-design-development", "technology-consulting", "managed-hosting-support"],
    relatedInsightSlugs: [],
    ctaVariant: "website-review",
    ctaContent: {
      eyebrow: "HOW DOES YOUR WEBSITE MEASURE UP?",
      heading: "Get a clearer direction for your website.",
      body: "We will review your website in the context of your business and identify the opportunities we believe are most worth your attention.",
      label: "Request a Website Review",
      href: "/contact",
    },
    content: greatSmallBusinessWebsiteContent,
  },
  {
    id: "website-redesign-checklist-15-signs-its-time-for-an-upgrade",
    slug: "website-redesign-checklist-15-signs-its-time-for-an-upgrade",
    title: "Website Redesign Checklist: 15 Signs It’s Time for an Upgrade",
    excerpt: "Use this 15-point checklist to identify design, usability, performance, content, and technical issues that may signal your business website needs an upgrade.",
    category: "Web Design",
    publishedAt: "2026-06-29",
    updatedAt: "2026-06-29",
    author: "Fractionl Studio",
    readingTime: calculateReadingTime(websiteRedesignChecklistContent),
    heroImage: "/images/insights/website-redesign-checklist-15-signs-its-time-for-an-upgrade/hero.webp",
    heroImageAlt: "Website redesign checklist showing design, mobile, speed, security, content, and usability issues.",
    heroImageWidth: 1672,
    heroImageHeight: 941,
    featured: false,
    status: "published",
    seoTitle: "Website Redesign Checklist: 15 Signs It’s Time to Upgrade",
    metaDescription: "Use this 15-point website redesign checklist to identify outdated design, poor usability, slow performance, technical problems, and missed opportunities.",
    canonicalUrl: "/insights/website-redesign-checklist-15-signs-its-time-for-an-upgrade",
    targetKeywords: ["website redesign checklist", "signs you need a website redesign", "when to redesign a website", "website redesign signs", "outdated website checklist", "signs your website needs an upgrade", "website refresh checklist", "business website redesign", "website redesign for small business", "how often should you redesign your website"],
    relatedServiceSlugs: ["website-design-development", "technology-consulting", "managed-hosting-support"],
    relatedInsightSlugs: [],
    ctaVariant: "website-review",
    content: websiteRedesignChecklistContent,
  },
  {
    id: "web-designer-vs-web-developer-which-one-does-your-business-need",
    slug: "web-designer-vs-web-developer-which-one-does-your-business-need",
    title: "Web Designer vs. Web Developer: Which One Does Your Business Need?",
    excerpt: "This article compares the responsibilities of web designers and web developers to help businesses decide whether they need one role or both.",
    category: "Web Design",
    publishedAt: "2026-06-29",
    updatedAt: "2026-06-29",
    author: "Fractionl Studio",
    readingTime: calculateReadingTime(webDesignerVsDeveloperContent),
    heroImage: "/images/insights/web-designer-vs-web-developer-which-one-does-your-business-need/hero.webp",
    heroImageAlt: "Side-by-side comparison of web design tools and web development code",
    heroImageWidth: 1672,
    heroImageHeight: 941,
    featured: false,
    status: "published",
    seoTitle: "Web Designer vs. Web Developer: Which Do You Need?",
    metaDescription: "Learn the difference between a web designer and web developer, what each role does, and whether your business needs one or both.",
    canonicalUrl: "/insights/web-designer-vs-web-developer-which-one-does-your-business-need",
    targetKeywords: ["web designer vs web developer", "difference between web designer and web developer", "do I need a web designer or web developer", "what does a web designer do", "what does a web developer do", "hire a web designer or developer", "web design vs web development", "website designer and developer", "web designer for small business", "web developer for small business"],
    relatedServiceSlugs: ["website-design-development", "fractional-product-design", "technology-consulting"],
    relatedInsightSlugs: [],
    ctaVariant: "project",
    ctaContent: { eyebrow: "NEED DESIGN, DEVELOPMENT, OR BOTH?", heading: "Bring the right disciplines together for the work.", body: "Tell us what you are building, where the project stands, and what your business needs. Fractionl Studio can help with design, development, or connected support across both.", label: "Start a Project", href: "/contact" },
    content: webDesignerVsDeveloperContent,
  },
  {
    id: "website-maintenance-explained-what-every-business-owner-should-know",
    slug: "website-maintenance-explained-what-every-business-owner-should-know",
    title: "Website Maintenance Explained: What Every Business Owner Should Know",
    excerpt: "Learn how updates, security, backups, performance checks, and ongoing support help keep a business website healthy after launch.",
    category: "Web Development",
    publishedAt: "2026-06-29",
    updatedAt: "2026-06-29",
    author: "Fractionl Studio",
    readingTime: calculateReadingTime(websiteMaintenanceContent),
    heroImage: "/images/insights/website-maintenance-explained-what-every-business-owner-should-know/hero.webp",
    heroImageAlt: "Business website maintenance dashboard showing updates, security, backups, uptime, and routine monitoring.",
    heroImageWidth: 1731,
    heroImageHeight: 909,
    featured: false,
    status: "published",
    seoTitle: "Website Maintenance Explained for Business Owners | Fractionl Studio",
    metaDescription: "Learn what website maintenance includes, why updates, security, backups, and monitoring matter, and how ongoing support protects your site.",
    canonicalUrl: "/insights/website-maintenance-explained-what-every-business-owner-should-know",
    targetKeywords: ["website maintenance explained", "what is website maintenance", "website maintenance for small business", "website maintenance services", "WordPress maintenance", "website updates and backups", "website security maintenance", "ongoing website support", "business website maintenance", "website care plan"],
    relatedServiceSlugs: ["managed-hosting-support", "website-design-development", "technology-consulting"],
    relatedInsightSlugs: [],
    ctaVariant: "project",
    ctaContent: {
      eyebrow: "NEED ONGOING WEBSITE SUPPORT?",
      heading: "Keep your website secure, updated, and working properly.",
      body: "Fractionl Studio provides managed hosting and ongoing support for businesses that want experienced help looking after the technical details.",
      label: "Explore Managed Hosting & Support",
      href: "/services/managed-hosting-support",
    },
    content: websiteMaintenanceContent,
  },
  {
    id: "10-signs-your-website-is-costing-you-customers",
    slug: "10-signs-your-website-is-costing-you-customers",
    title: "10 Signs Your Website Is Costing You Customers",
    excerpt: "Learn how to recognize website issues that may be weakening trust, reducing inquiries, or losing sales—and when a redesign may be worth considering.",
    category: "Web Design",
    publishedAt: "2026-06-29",
    updatedAt: "2026-06-29",
    author: "Fractionl Studio",
    readingTime: calculateReadingTime(websiteCostingCustomersContent),
    heroImage: "/images/insights/10-signs-your-website-is-costing-you-customers/hero.webp",
    heroImageAlt: "Business website mockup annotated with slow load, mobile friction, low trust, excessive clutter, and a weak call to action",
    heroImageWidth: 1731,
    heroImageHeight: 909,
    featured: false,
    status: "published",
    seoTitle: "10 Signs Your Website Is Costing You Customers | Fractionl Studio",
    metaDescription: "Discover 10 signs your website may be losing customers, damaging trust, or creating friction—and learn when it may be time for a redesign.",
    canonicalUrl: "/insights/10-signs-your-website-is-costing-you-customers",
    targetKeywords: ["signs your website is costing you customers", "signs you need a new website", "outdated website", "website losing customers", "website redesign", "poor website user experience", "signs your website needs a redesign"],
    relatedServiceSlugs: ["website-design-development", "technology-consulting"],
    relatedInsightSlugs: [],
    ctaVariant: "website-review",
    content: websiteCostingCustomersContent,
  },
  {
    id: "how-long-does-it-take-to-build-a-website",
    slug: "how-long-does-it-take-to-build-a-website",
    title: "How Long Does It Take to Build a Website?",
    excerpt: "A realistic look at the stages that shape a custom website timeline, from discovery and design through development, testing, and launch.",
    category: "Web Design",
    publishedAt: "2026-07-20",
    author: "Fractionl Studio",
    readingTime: calculateReadingTime(websiteTimelineContent),
    heroImage: "/images/insights/how-long-does-it-take-to-build-a-website/hero.webp",
    heroImageWidth: 1672,
    heroImageHeight: 941,
    heroImageAlt: "Website interface mockup with a callout reading Typical timeline: 6–10 weeks",
    featured: true,
    status: "published",
    seoTitle: "How Long Does It Take to Build a Website? | Fractionl Studio",
    metaDescription: "Learn what affects a website project timeline, how long each stage can take, and what businesses can do to keep a website design and development project moving.",
    canonicalUrl: "/insights/how-long-does-it-take-to-build-a-website",
    targetKeywords: ["how long does it take to build a website", "website development timeline", "how long does website design take", "website project timeline", "how long to build a custom website"],
    relatedServiceSlugs: ["website-design-development", "technology-consulting"],
    relatedInsightSlugs: [],
    ctaVariant: "project",
    content: websiteTimelineContent,
  },
  {
    id: "how-to-choose-the-right-web-designer-for-your-business",
    slug: "how-to-choose-the-right-web-designer-for-your-business",
    title: "How to Choose the Right Web Designer for Your Business",
    excerpt: "Learn how to compare web designers, ask better questions, and choose the right fit for your business without deciding on price or appearance alone.",
    category: "Web Design",
    publishedAt: "2026-06-29",
    updatedAt: "2026-06-29",
    author: "Fractionl Studio",
    readingTime: calculateReadingTime(choosingWebDesignerContent),
    heroImage: "/images/insights/how-to-choose-the-right-web-designer-for-your-business/hero.webp",
    heroImageAlt: "Website design proposals and evaluation criteria used to compare potential web designers.",
    heroImageWidth: 1731,
    heroImageHeight: 909,
    featured: false,
    status: "published",
    seoTitle: "How to Choose the Right Web Designer for Your Business",
    metaDescription: "Learn what to look for in a web designer, which questions to ask, and how to choose the right fit for your business, goals, and website project.",
    canonicalUrl: "/insights/how-to-choose-the-right-web-designer-for-your-business",
    targetKeywords: ["how to choose a web designer", "how to choose the right web designer", "choosing a web designer for your business", "hire a web designer", "questions to ask a web designer", "what to look for in a web designer", "web designer for small business", "freelance web designer vs web design company", "finding a web designer", "website designer Canada"],
    relatedServiceSlugs: ["website-design-development", "technology-consulting"],
    relatedInsightSlugs: [],
    ctaVariant: "project",
    ctaContent: {
      eyebrow: "LOOKING FOR THE RIGHT FIT?",
      heading: "Start with a conversation about the work.",
      body: "Tell us what you are building, what your business needs, and what you want the website to accomplish. We will help you determine whether Fractionl is the right fit.",
      label: "Start a Project",
      href: "/contact",
    },
    content: choosingWebDesignerContent,
  },
  {
    id: "should-you-build-your-own-website-or-hire-a-professional",
    slug: "should-you-build-your-own-website-or-hire-a-professional",
    title: "Should You Build Your Own Website or Hire a Professional?",
    excerpt: "Compare DIY website builders with professional web design to decide which approach best fits your goals, budget, and website complexity.",
    category: "Web Design",
    publishedAt: "2026-06-29",
    updatedAt: "2026-06-29",
    author: "Fractionl Studio",
    readingTime: calculateReadingTime(buildOrHireContent),
    heroImage: "/images/insights/should-you-build-your-own-website-or-hire-a-professional/hero.webp",
    heroImageAlt: "Comparison between a DIY website builder and a professionally designed custom website",
    heroImageWidth: 1731,
    heroImageHeight: 909,
    featured: false,
    status: "published",
    seoTitle: "Build Your Own Website or Hire a Professional? | Fractionl Studio",
    metaDescription: "Compare building your own website with hiring a professional, including cost, time, quality, flexibility, and which option fits your business.",
    canonicalUrl: "/insights/should-you-build-your-own-website-or-hire-a-professional",
    targetKeywords: ["should you build your own website or hire a professional", "DIY website vs professional web designer", "build your own website vs hire someone", "should I hire a web designer", "DIY website builder", "professional website design", "website builder vs web designer", "hire someone to build my website", "is a professional website worth it", "small business DIY website"],
    relatedServiceSlugs: ["website-design-development", "technology-consulting"],
    relatedInsightSlugs: [],
    ctaVariant: "project",
    ctaContent: {
      eyebrow: "DECIDED YOU NEED PROFESSIONAL HELP?",
      heading: "Build a website around what your business actually needs.",
      body: "Tell us what you are building, what your website needs to accomplish, and where the current approach is falling short.",
      label: "Start a Project",
      href: "/contact",
    },
    content: buildOrHireContent,
  },
  {
    id: "website-hosting-explained-what-every-business-owner-needs-to-know",
    slug: "website-hosting-explained-what-every-business-owner-needs-to-know",
    title: "Website Hosting Explained: What Every Business Owner Needs to Know",
    excerpt: "A plain-language guide to help business owners understand website hosting, domains, performance, security, and ongoing website support.",
    category: "Web Development",
    publishedAt: "2026-06-29",
    updatedAt: "2026-06-29",
    author: "Fractionl Studio",
    readingTime: calculateReadingTime(websiteHostingExplainedContent),
    heroImage: "/images/insights/website-hosting-explained-what-every-business-owner-needs-to-know/hero.webp",
    heroImageAlt: "Website connected to server and cloud hosting with indicators for reliability, storage, speed, support, and worldwide availability",
    heroImageWidth: 1672,
    heroImageHeight: 941,
    featured: false,
    status: "published",
    seoTitle: "Website Hosting Explained for Business Owners | Fractionl Studio",
    metaDescription: "Learn what website hosting is, how it works, how it differs from a domain, and what businesses should consider when choosing hosting.",
    canonicalUrl: "/insights/website-hosting-explained-what-every-business-owner-needs-to-know",
    targetKeywords: ["website hosting explained", "what is website hosting", "website hosting for small business", "how website hosting works", "business website hosting", "managed website hosting", "WordPress hosting", "domain vs hosting", "website hosting and maintenance", "choosing a website host"],
    relatedServiceSlugs: ["managed-hosting-support", "website-design-development", "technology-consulting"],
    relatedInsightSlugs: [],
    ctaVariant: "project",
    ctaContent: {
      eyebrow: "NEED RELIABLE WEBSITE SUPPORT?",
      heading: "Keep your website secure, updated, and running smoothly.",
      body: "Fractionl Studio provides managed hosting and ongoing support for businesses that want someone experienced looking after the technical details.",
      label: "Explore Managed Hosting & Support",
      href: "/services/managed-hosting-support",
    },
    content: websiteHostingExplainedContent,
  },
  {
    id: "development-template-preview",
    slug: "development-template-preview",
    title: "A practical guide to planning a digital improvement",
    excerpt: "Generic demonstration content used to verify the article template before real editorial content is published.",
    category: "Web Design",
    publishedAt: "2026-01-01",
    updatedAt: "2026-01-01",
    author: "Fractionl Studio",
    readingTime: "5 min read",
    featured: false,
    status: "draft",
    seoTitle: "Development Template Preview | Fractionl Studio",
    metaDescription: "A noindex development preview of the Fractionl Studio Insights article template.",
    targetKeywords: [],
    relatedServiceSlugs: ["website-presence"],
    relatedInsightSlugs: [],
    ctaVariant: "website-review",
    content: [
      { type: "paragraph", text: "This draft uses generic content to demonstrate the reading experience. It is not a published Fractionl Studio insight." },
      { type: "h2", text: "Start with the decision" },
      { type: "paragraph", text: "Define the decision the work needs to support before discussing pages, features, or technology. A clear decision gives the project a useful boundary." },
      { type: "callout", heading: "A useful prompt", text: "What should a customer or team member be able to understand or do more easily when this work is complete?" },
      { type: "h2", text: "Separate needs from ideas" },
      { type: "paragraph", text: "Collect ideas without treating every idea as a requirement. Then group them by the user need or business need they address." },
      { type: "unordered-list", items: ["Clarify the audience", "Name the current friction", "Identify the most useful next action"] },
      { type: "inline-cta" },
      { type: "h2", text: "Choose a sensible first version" },
      { type: "paragraph", text: "A focused first version creates something concrete to review and improve. It also makes effort, tradeoffs, and responsibilities easier to understand." },
      { type: "table", headers: ["Question", "Purpose"], rows: [["What is essential?", "Protect the core outcome"], ["What can wait?", "Keep scope workable"]] },
      { type: "h2", text: "Create a clear next step" },
      { type: "paragraph", text: "Document the chosen direction, the unresolved questions, and who owns the next action. Good planning should make movement easier." },
    ],
  },
];

export const publishedInsights = insights
  .filter((insight): insight is Insight & { publishedAt: string } => insight.status === "published" && typeof insight.publishedAt === "string" && Number.isFinite(Date.parse(insight.publishedAt)))
  .sort((a, b) => Date.parse(b.publishedAt) - Date.parse(a.publishedAt));

export function getInsightBySlug(slug?: string) {
  return insights.find((insight) => insight.slug === slug);
}

export function toHeadingId(value: string) {
  return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
