<?php
/** React-parity About page. @package Fractionl_Studio */
get_header();
$members = fractionl_option( 'team_members', array() );
?>
<div class="about-page">
<section class="about-page__hero"><div class="container about-page__hero-grid"><div class="about-page__hero-copy reveal"><p class="eyebrow">About Fractionl Studio</p><h1>Built to work <span>alongside you.</span></h1></div><div class="about-page__hero-note reveal"><p>A small, experienced design and development studio for businesses and teams that need more digital capacity—without building it all in-house.</p><a href="#about-fractionl" class="about-page__jump">Get to know the studio <span aria-hidden="true">↓</span></a></div></div></section>
<section class="about-studio" id="about-fractionl"><div class="container"><p class="eyebrow reveal">About Fractionl Studio</p><div class="about-studio__grid"><div class="about-studio__statement reveal"><h2>Experienced digital support, without building the whole team in-house.</h2></div><div class="about-studio__body reveal"><p>Fractionl Studio brings design, development, and digital strategy together to help businesses build, improve, and support the technology behind their work.</p><p>We work with founders bringing new ideas to market, businesses replacing outdated websites or manual systems, and teams that need experienced capacity without another permanent hire.</p><p>From websites and digital products to ongoing design, development, and technical support, we step in where the need is—for a project, a temporary gap, or ongoing support.</p></div></div><div class="about-studio__visual reveal" aria-label="Fractionl Studio works alongside client teams from need through delivery"><div class="about-studio__visual-top"><span>Your team</span><span>Working together</span><span>Fractionl Studio</span></div><div class="about-studio__visual-flow" aria-hidden="true"><div><b>01</b><span>A need appears</span></div><i></i><div><b>02</b><span>We plug in</span></div><i></i><div><b>03</b><span>The work moves</span></div></div></div></div></section>
<section class="about-support"><div class="container about-support__grid"><div class="about-support__intro reveal"><p class="eyebrow">Why Fractionl exists</p><h2>You do not always need another full-time hire.</h2><p>Sometimes the right experience is needed for a specific moment. Fractionl Studio is designed to work alongside businesses and teams in those moments—without adding unnecessary overhead or slowing the work down.</p></div><div class="about-support__list">
<?php foreach ( array( 'A team to plan and build something new', 'Experienced support for a specific project', 'Coverage during a leave, launch, or capacity gap', 'Ongoing design, development, or creative support' ) as $index => $item ) : ?><div class="about-support__item reveal"><span>0<?php echo esc_html( $index + 1 ); ?></span><p><?php echo esc_html( $item ); ?></p></div><?php endforeach; ?>
</div></div></section>
<section class="team team--page page-section"><div class="container"><div class="section-head section-head--wide reveal"><p class="eyebrow">The people</p><h2 class="section-title">The people behind the work.</h2><p class="section-intro page-intro">Fractionl Studio combines product design, web design, software development, and digital strategy. We stay closely involved in the work and bring in additional specialists only when a project genuinely requires them.</p></div><div class="team-grid">
<?php foreach ( is_array( $members ) ? $members : array() as $i => $member ) : $fallback = 0 === $i ? 'nicole.jpeg' : 'nick.avif'; ?><article class="team-card reveal"><img class="team-photo" src="<?php echo esc_url( ! empty( $member['photo'] ) ? wp_get_attachment_image_url( (int) $member['photo'], 'full' ) : fractionl_asset_url( 'images/' . $fallback ) ); ?>" alt="<?php echo esc_attr( $member['photo_alt'] ?? ( $member['name'] ?? '' ) ); ?>" loading="lazy"><div class="team-info"><h3 class="team-name"><?php echo esc_html( $member['name'] ?? '' ); ?></h3><p class="team-role"><?php echo esc_html( $member['role'] ?? '' ); ?></p><p class="team-bio"><?php echo esc_html( $member['bio'] ?? '' ); ?></p><?php if ( ! empty( $member['skills'] ) ) : ?><ul class="team-tags"><?php foreach ( $member['skills'] as $tag ) : ?><li><?php echo esc_html( is_array( $tag ) ? ( $tag['skill'] ?? '' ) : $tag ); ?></li><?php endforeach; ?></ul><?php endif; ?><div class="team-actions"><a class="team-link team-link--primary" href="<?php echo esc_url( $member['portfolio'] ?? '#' ); ?>" target="_blank" rel="noopener">View Portfolio <span aria-hidden="true">↗</span></a><a class="team-link" href="<?php echo esc_url( $member['linkedin'] ?? '#' ); ?>" target="_blank" rel="noopener">LinkedIn</a><a class="team-link" href="mailto:<?php echo esc_attr( $member['email'] ?? '' ); ?>">Email</a></div></div></article><?php endforeach; ?>
</div></div></section>
<section class="about-page__cta"><div class="container about-page__cta-inner"><div class="reveal"><p class="eyebrow">Work with Fractionl</p><h2>Bring experienced support to the table.</h2></div><div class="about-page__cta-action reveal"><p>Tell us what you are building, where your team needs capacity, or what needs to keep moving.</p><?php fractionl_tally_button( 'Start a Project ↗', 'btn btn-primary btn-lg' ); ?></div></div></section>
</div>
<?php get_footer();
