<?php /** React-parity Services page. @package Fractionl_Studio */ get_header();
$services = array(
	array( '01', 'technology-consulting', 'Technology Consulting', 'strategy', 'We help you decide what to build, what to buy, and what to skip before you spend money on development — so the technical decisions match the business problem you’re actually trying to solve.', 'Product strategy, MVP planning, system architecture, vendor & platform selection' ),
	array( '02', 'website-design-development', 'Website Design & Development', 'website', 'We design and build custom websites built to convert — fast load times, clear paths to contact or purchase, and a structure you can update yourself without calling us for every change.', 'New businesses, redesigns, service businesses, professional firms, local businesses' ),
	array( '03', 'web-applications', 'Web Applications', 'application', 'We design and build custom web applications that replace manual work with systems — dashboards, customer portals, booking flows, billing, and internal tools that cut down the hours your team spends on repetitive tasks.', 'Founders building a SaaS product, businesses with software that has outgrown its current support or development team' ),
	array( '04', 'fractional-product-design', 'Fractional Product Design & Development', 'product', 'Experienced product design and development support for launches, product initiatives, team gaps, leave coverage, overflow, and ongoing digital work.', 'Internal teams, agencies, founders, and businesses that need experienced capacity' ),
	array( '05', 'creative-retainer', 'Creative Retainer', 'creative', 'A reserved block of design support each month, handled by a team that already knows your brand — so campaigns, landing pages, and sales collateral get done without briefing a new freelancer every time.', 'Businesses that need consistent creative output without an in-house hire' ),
	array( '06', 'managed-hosting-support', 'Managed Hosting & Ongoing Support', 'support', 'We keep what we build — or what you already have — online, secure, and fast: backups, monitoring, updates, and a team that responds when something breaks.', 'Any business that doesn’t want website maintenance to become someone’s job' ),
); ?>
<div class="services-overview"><section class="services-overview__hero"><div class="container services-overview__hero-grid"><div class="services-overview__hero-copy reveal"><p class="eyebrow">Strategy · Design · Development · Support</p><h1>From first decision to <span>long-term momentum.</span></h1></div><div class="services-overview__hero-aside reveal"><p>Fractionl Studio helps ambitious businesses and product teams plan, design, build, and care for the digital work that moves them forward.</p><a class="services-overview__jump" href="#service-overview">Explore our services <span aria-hidden="true">↓</span></a></div><div class="services-overview__hero-map reveal" aria-hidden="true"><span>Clarify</span><i></i><span>Design</span><i></i><span>Build</span><i></i><span>Grow</span></div></div></section>
<section class="services-overview__intro"><div class="container services-overview__intro-grid"><p class="eyebrow reveal">One studio, the full picture</p><p class="reveal">Bring us in at the beginning, in the middle of a build, or when the work needs consistent attention. We connect business strategy to clear design, capable technology, and support that lasts beyond launch.</p></div></section>
<section class="services-overview__list" id="service-overview" aria-label="Services"><?php foreach ( $services as $service ) : ?><article class="overview-service overview-service--<?php echo esc_attr( $service[3] ); ?>"><div class="container overview-service__grid"><div class="overview-service__copy reveal"><span class="overview-service__number"><?php echo esc_html( $service[0] ); ?></span><h2><?php echo esc_html( $service[2] ); ?></h2><p class="overview-service__description"><?php echo esc_html( $service[4] ); ?></p><p class="overview-service__best"><strong>Best for</strong><?php echo esc_html( $service[5] ); ?></p><a class="overview-service__link" href="<?php echo esc_url( home_url( '/services/' . $service[1] . '/' ) ); ?>">Learn more <span aria-hidden="true">↗</span></a></div><div class="overview-service__visual reveal"><?php get_template_part( 'template-parts/service/visual', null, array( 'type' => $service[3] ) ); ?></div></div></article><?php endforeach; ?></section>
<section class="engagements"><div class="container"><div class="engagements__heading reveal"><p class="eyebrow">Ways to work with us</p><h2>The right shape of support for where you are now.</h2></div><div class="engagements__track"><?php foreach ( array( array( 'One-off project', 'A focused engagement with a clear outcome, from strategy and design through launch.' ), array( 'Temporary or fractional support', 'Senior capacity embedded with your team for a project, a quarter, or a coverage gap.' ), array( 'Ongoing support', 'A familiar studio on hand each month to keep creative and technical work moving.' ) ) as $i => $model ) : ?><article class="engagements__item reveal"><span>0<?php echo esc_html( $i + 1 ); ?></span><h3><?php echo esc_html( $model[0] ); ?></h3><p><?php echo esc_html( $model[1] ); ?></p></article><?php endforeach; ?></div></div></section>
<section class="contact"><div class="container contact-inner"><p class="eyebrow reveal">Get in touch</p><h2 class="contact-title reveal">Need a digital partner you can actually rely on?</h2><p class="contact-text reveal">Whether you need website support, marketing assets, product design, or ongoing digital help, we can help you choose the right starting point.</p><div class="contact-actions reveal"><?php fractionl_tally_button( 'Start a Project', 'btn btn-primary btn-lg' ); ?><a class="btn btn-ghost btn-lg" href="<?php echo esc_url( fractionl_get_page_url( 'work', '/work/' ) ); ?>">View Sample Work</a></div></div></section></div>
<?php get_footer();
