<?php /** React-parity Contact page. @package Fractionl_Studio */ get_header();
$options = array(
	array( 'Website Design & Development', 'For a new business website, landing page, redesign, WordPress build, or an existing website that needs to work better.' ),
	array( 'Web Application or MVP', 'For SaaS products, customer portals, dashboards, booking systems, internal tools, and technology-enabled business ideas.' ),
	array( 'Product Design & Team Support', 'For UX/UI design, user flows, prototypes, design systems, project overflow, or temporary product design capacity.' ),
	array( 'Ongoing Creative or Technical Support', 'For recurring creative work, managed hosting, website maintenance, updates, development support, and ongoing digital improvements.' ),
); ?>
<section class="contact-page-hero"><div class="container contact-page-hero__inner"><p class="eyebrow reveal">Contact</p><h1 class="page-title contact-page-title reveal">Tell us what you are building—or what is no longer working.</h1><p class="page-hero-sub contact-page-sub reveal">Whether you are launching a new business, replacing an outdated website, building a digital product, or adding experienced capacity to your team, send us a short note about what you need.</p><div class="hero-actions reveal"><?php fractionl_tally_button(); ?><a href="<?php echo esc_url( fractionl_get_page_url( 'services', '/services/' ) ); ?>" class="btn btn-ghost">View Services</a></div></div></section>
<section class="services contact-page-section contact-page-section--tint"><div class="container"><div class="section-head section-head--wide reveal"><p class="eyebrow">Inquiry options</p><h2 class="section-title">What can we help with?</h2></div><div class="services-grid contact-options-grid"><?php foreach ( $options as $option ) : ?><article class="service-card contact-option-card reveal"><h3 class="service-title"><?php echo esc_html( $option[0] ); ?></h3><p class="service-desc"><?php echo esc_html( $option[1] ); ?></p><?php fractionl_tally_button( 'Start an Inquiry', 'card-link contact-card-cta' ); ?></article><?php endforeach; ?></div></div></section>
<section class="contact-page-section contact-page-section--white"><div class="container contact-info-grid"><div class="reveal"><p class="eyebrow">Helpful details</p><h2 class="section-title">What should you include?</h2><p class="section-intro">You do not need to have everything figured out. A short message is enough to start.</p></div><div class="reveal"><ul class="compact-list contact-checklist"><li>Your business, product, or organization</li><li>What you are hoping to build, improve, or replace</li><li>Who will use it</li><li>Any timeline, budget range, or launch date already in mind</li><li>The best way to reach you</li></ul></div></div></section>
<section class="process contact-page-section contact-page-section--tint"><div class="container"><div class="section-head section-head--wide reveal"><p class="eyebrow">What happens next</p><h2 class="section-title">A straightforward next step.</h2></div><ol class="process-list"><?php foreach ( array( array( 'Send an Inquiry', 'Tell us what you need help with and share any context you already have.' ), array( 'We Review the Request', 'We look at the business need, scope, timing, and type of support that may be the best fit.' ), array( 'We Follow Up', 'If the project looks like a good fit, we will reach out with next steps, questions, or a recommended approach.' ) ) as $i => $step ) : ?><li class="process-step reveal"><span class="process-num">0<?php echo esc_html( $i + 1 ); ?></span><div class="process-body"><h3 class="process-title"><?php echo esc_html( $step[0] ); ?></h3><p class="process-desc"><?php echo esc_html( $step[1] ); ?></p></div></li><?php endforeach; ?></ol></div></section>
<section class="contact-page-section contact-page-section--white"><div class="container contact-info-grid"><div class="reveal"><p class="eyebrow">Alternative contact</p><h2 class="section-title">Prefer email?</h2><p class="section-intro">You can also reach us directly.</p></div><div class="contact-direct reveal"><p class="footer-label">Email</p><a class="contact-direct__link" href="mailto:hello@fractionlstudio.com">hello@fractionlstudio.com</a><p class="footer-label">Location</p><p>Edmonton, Alberta</p><p>Working with clients across Canada and remotely.</p></div></div></section>
<section class="contact"><div class="container contact-inner"><h2 class="contact-title reveal">Ready to start?</h2><p class="contact-text reveal">Use the inquiry button to tell us what you are working on. We will take it from there.</p><div class="contact-actions reveal"><?php fractionl_tally_button( 'Start a Project', 'btn btn-primary btn-lg' ); ?></div></div></section>
<?php get_footer();
