<?php /** React-parity Work page. @package Fractionl_Studio */ get_header();
$project_order = array( 'trifold-brochure', 'navigation-restructure', 'pensioner-profile', 'restaurant-website-redesign', 'innquest-canada', 'message-blast' );
$projects = new WP_Query( array( 'post_type' => 'case_study', 'post_status' => 'publish', 'posts_per_page' => 6, 'post_name__in' => $project_order, 'orderby' => 'post_name__in' ) );
$demos = array(
	array( 'Maya Bennett Real Estate', 'Independent Realtor', 'A personal brand website for an independent realtor, featuring listings, buying and selling pages, lead capture, and a single property listing page.', 'https://maya-bennett.vercel.app/' ),
	array( 'Serene Paths Clinic', 'Therapist / Coach / Wellness Provider', 'A calm, professional website for a therapist, coach, or wellness provider, featuring services, resources, consultation booking, and trust-building content.', 'https://serene-paths.vercel.app/' ),
	array( 'North Peak Coffee Co.', 'Local Ecommerce', 'A small ecommerce website for a local coffee roaster, featuring product browsing, product detail pages, cart experience, and brand storytelling.', 'https://north-peak-coffee-co.vercel.app/' ),
); ?>
<div class="work-page"><header class="page-hero"><div class="container"><p class="eyebrow reveal">Selected work</p><h1 class="page-title reveal">Selected Work</h1><p class="page-hero-sub reveal">A mix of studio projects, founder work, and demos showing what we build.</p></div></header>
<section class="work-collection work-collection--studio-work"><div class="container"><div class="section-head section-head--wide reveal"><p class="eyebrow">Selected work</p><h2 class="section-title">Studio Work</h2></div><div class="work-grid">
<?php while ( $projects->have_posts() ) : $projects->the_post(); get_template_part( 'template-parts/cards/card', 'case_study' ); endwhile; wp_reset_postdata(); ?>
<?php foreach ( $demos as $demo ) : $is_maya = str_starts_with( $demo[0], 'Maya' ); $is_serene = str_starts_with( $demo[0], 'Serene' ); ?><article class="work-card reveal"><a class="project-visual <?php echo $is_maya ? 'project-visual--realty' : ( $is_serene ? 'project-visual--wellness' : 'project-visual--editorial' ); ?>" href="<?php echo esc_url( $demo[3] ); ?>" target="_blank" rel="noopener"><div class="project-browser"><div class="mock-browser-bar"><span></span><span></span><span></span><b><?php echo esc_html( $is_maya ? 'mayabennett.ca' : ( $is_serene ? 'serenepaths.ca' : 'northpeak.coffee' ) ); ?></b></div><?php if ( $is_maya ) : ?><div class="realty-page"><small>EDMONTON REAL ESTATE</small><strong>Find your place.</strong><span>Explore listings →</span></div><?php elseif ( $is_serene ) : ?><div class="wellness-page"><i></i><small>A calmer path forward</small><strong>Support for the season you’re in.</strong></div><?php else : ?><div class="editorial-page"><small>SMALL BATCH · ALBERTA</small><strong>Better mornings, roasted here.</strong><i></i></div><?php endif; ?></div></a><h3 class="work-title"><?php echo esc_html( $demo[0] ); ?></h3><p class="work-type"><span>DEMO SITE</span> · <?php echo esc_html( $demo[1] ); ?></p><p class="work-desc"><?php echo esc_html( $demo[2] ); ?></p><a class="card-link" href="<?php echo esc_url( $demo[3] ); ?>" target="_blank" rel="noopener">View Demo <span aria-hidden="true">↗</span></a></article><?php endforeach; ?>
</div></div></section>
<section class="work-collection work-collection--founder-work work-collection--alternate"><div class="container"><div class="section-head section-head--wide reveal"><p class="eyebrow">Selected work</p><h2 class="section-title">Founder Work</h2></div><div class="work-grid work-grid--two"><?php foreach ( array( array( 'Nicole Buloran', 'Founder & Product Designer', '9+ years in product design, UX/UI, SaaS, and web.', 'https://nicole-buloran.com/work' ), array( 'Nick Castillo', 'Developer', 'Full-stack development, SaaS integrations, and software implementation.', 'https://nick-castillo.ca' ) ) as $founder ) : ?><article class="work-card reveal"><a class="project-visual" href="<?php echo esc_url( $founder[3] ); ?>" target="_blank" rel="noopener"><div class="founder-art"><i></i><i></i><i></i></div></a><h3 class="work-title"><?php echo esc_html( $founder[0] ); ?></h3><p class="work-type"><?php echo esc_html( $founder[1] ); ?></p><p class="work-desc"><?php echo esc_html( $founder[2] ); ?></p><a class="card-link" href="<?php echo esc_url( $founder[3] ); ?>" target="_blank" rel="noopener">View Portfolio <span aria-hidden="true">↗</span></a></article><?php endforeach; ?></div></div></section>
<section class="work-cta"><div class="container work-cta-inner"><h2 class="work-cta-title reveal">Want something like this for your business?</h2><div class="reveal"><?php fractionl_tally_button( 'Start a Project', 'btn btn-primary btn-lg' ); ?></div></div></section></div>
<?php get_footer();
